name = "cf-videox"
main = "worker/src/index.js"
compatibility_date = "2026-08-01"
workers_dev = true

[[rules]]
type = "ESModule"
globs = ["**/*.js"]
fallthrough = true

[assets]
directory = "frontend/dist"
not_found_handling = "single-page-application"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "videox"
database_id = "8fd98930-58f7-42a8-980e-75a788b307f5"
migrations_dir = "worker/migrations"

[vars]
VIDEOX_DEPLOYMENT = "cloudflare"
