name = "cf-videox"
main = "worker/src/index.js"
compatibility_date = "2026-08-01"
workers_dev = true

[[rules]]
type = "ESModule"
globs = ["**/*.js"]
fallthrough = true

[assets]
directory = "frontend/dist"
not_found_handling = "single-page-application"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "videox"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "worker/migrations"

[vars]
VIDEOX_DEPLOYMENT = "cloudflare"
